name: Lerna deployment test

on:
  push:
    branches:
      - master

jobs:
  install-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14

      - name: Install deps
        run: |
          yarn install

      - name: Lerna bootstrap
        run: |
          yarn run bootstrap

  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish package
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          yarn run publish
